name: CI

on: [push, pull_request]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: sqlite, intl, mbstring, xml, zip
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check coding standards (optional)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run tests (PHPUnit)
        run: vendor/bin/phpunit
